feira/config/routes.rb
Rails.application.routes.draw do
  resources :avaliacao_feirantes
  resources :avaliacao_shoppings
  resources :messages
  resources :shoppings
  resources :avaliacaos
  resources :wish_lists, only: [ :index, :create, :destroy ]
  resources :produtos
  resources :feirantes
  resources :administradors
  resources :users

  root "home#start_page" # Página inicial
  get "home/start_page" => "home#start_page", as: :start_page  
  get "home/login" => "home#login"
  get "home/feira" => "home#feira"
  get "home/feira/sort" => "home#feira", as: :sort_feira
  get "home/feirantes/:shopping_id" => "home#feirantes", as: :home_feirantes
  get "home/produtos_feirantes/:feirante_id" => "home#produtos_feirantes", as: :produtos_feirantes
  get "home/anotacoes" => "home#anotacoes"
  get "home/adicionar/:produto_id" => "home#adicionar", as: :adicionar
  get "home/admin_homepage" => "home#admin_homepage", as: :home_admin_homepage
  get "home/feirante_homepage" => "home#feirante_homepage", as: :home_feirante_homepage
  get "home/admin_feirantes" => "home#admin_feirantes", as: :home_admin_feirantes

  get "login", to: "home#login"
  post "login", to: "home#authenticate"
  delete "logout", to: "home#logout"
  post "create_temp_user", to: "home#create_temp_user"
  post 'users/create_temp_user', to: 'users#create_temp_user'

  get "up" => "rails/health#show", as: :rails_health_check
end

feira/app/models/feirante.rb
# Class representing a vendor/merchant in a shopping center.
# This class manages vendor information and their relationships.
#
#
# Associations:
# - Belongs to a shopping center
# - Has many products that are dependent on vendor (will be destroyed if vendor is deleted)
#
# Security:
# - Implements secure password functionality through has_secure_password
class Feirante < ApplicationRecord
  has_secure_password
  belongs_to :shopping
  has_many :produtos, dependent: :destroy
  has_many :avaliacao_feirantes, dependent: :destroy
  has_one_attached :image

  validates :email, presence: true, 
    format: { with: /@/, message: "deve incluir um '@'" }

  def average_rating
    avaliacao_feirantes.average(:nota).to_f.round(2)
  end

  def user_has_reviewed?(user)
    avaliacao_feirantes.exists?(user: user)
  end

  def user_review(user)
    avaliacao_feirantes.find_by(user: user)
  end
end

feira/app/controllers/feirantes_controller.rb
class FeirantesController < ApplicationController
  before_action :set_feirante, only: %i[show edit update destroy]

  # GET /feirantes or /feirantes.json
  def index
    @feirantes = Feirante.all
  end

  # GET /feirantes/1 or /feirantes/1.json
  def show
  end

  # GET /feirantes/new
  def new
    @feirante = Feirante.new
  end

  # GET /feirantes/1/edit
  def edit
  end

  # POST /feirantes or /feirantes.json
  def create
    @feirante = Feirante.new(feirante_params)

    respond_to do |format|
      if @feirante.save
        redirect_to home_admin_feirantes_path(shopping_id: @feirante.shopping_id), notice: "Feirante criado com sucesso."

      else
        render :new
      end
    end
  end

  # PATCH/PUT /feirantes/1 or /feirantes/1.json
  def update
    respond_to do |format|
      if @feirante.update(feirante_params)
        format.html { redirect_to home_admin_feirantes_path, notice: "Feirante was successfully updated." }
        format.json { render :show, status: :ok, location: @feirante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feirante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feirantes/1 or /feirantes/1.json
  def destroy
    @feirante.destroy

    respond_to do |format|
      format.html { redirect_to home_admin_feirantes_path, notice: "Feirante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feirante
      @feirante = Feirante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feirante_params
      params.require(:feirante).permit(:nome, :email, :password, :password_confirmation, :descricao, :shopping_id, :categoria, :image)
    end
end

feira/app/helpers/feirantes_helper.rb
module FeirantesHelper
end

feira/app/views/feirantes/_feirante.html.erb
<div id="<%= dom_id feirante %>">
  <p>
    <strong>Nome:</strong>
    <%= feirante.nome %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= feirante.email %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= feirante.password %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= feirante.descricao %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= feirante.categoria %>
  </p>


</div>

feira/app/views/feirantes/_form.html.erb
<%= form_with(model: feirante, local: true) do |form| %>
  <% if feirante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feirante.errors.count, "error") %> prohibited this feirante from being saved:</h2>

      <ul>
        <% feirante.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.label :categoria, style: "display: block" %>
    <%= form.text_field :categoria %>
  </div>
  

  <div>
    <%= form.label :shopping_id, "Shopping", style: "display: block" %>
    <%= form.collection_select :shopping_id, Shopping.all, :id, :nome, prompt: "Selecione um Shopping" %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

feira/app/views/feirantes/edit.html.erb
<% content_for :title, "Editing feirante" %>

<h1>Editing feirante</h1>

<%= render "form", feirante: @feirante %>

<br>

<div>
  <% if current_admin %>
    <%= link_to "Back", :back %>
  <% end %>
</div>

feira/app/views/feirantes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Feirantes" %>

<h1>Feirantes</h1>

<div id="feirantes">
  <% @feirantes.each do |feirante| %>
    <%= render feirante %>
    <p>
      <%= link_to "Show this feirante", feirante %>
    </p>
  <% end %>
</div>

<%= link_to "New feirante", new_feirante_path %>

feira/app/views/feirantes/new.html.erb
<% content_for :title, "New feirante" %>

<h1>New feirante</h1>

<%= render "form", feirante: @feirante %>

<br>

<div>
  <%= link_to "Voltar", home_admin_homepage_path %>
</div>

feira/app/views/feirantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @feirante %>

<div>
  <%= link_to "Edit this feirante", edit_feirante_path(@feirante) %> |
  <%= link_to "Back to feirantes", feirantes_path %>

  <%= button_to "Destroy this feirante", @feirante, method: :delete %>
</div>