feira/config/routes.rb
Rails.application.routes.draw do
  resources :avaliacao_feirantes
  resources :avaliacao_shoppings
  resources :messages
  resources :shoppings
  resources :avaliacaos
  resources :wish_lists, only: [ :index, :create, :destroy ]
  resources :produtos
  resources :feirantes
  resources :administradors
  resources :users

  root "home#start_page" # Página inicial
  get "home/start_page" => "home#start_page", as: :start_page  
  get "home/login" => "home#login"
  get "home/feira" => "home#feira"
  get "home/feira/sort" => "home#feira", as: :sort_feira
  get "home/feirantes/:shopping_id" => "home#feirantes", as: :home_feirantes
  get "home/produtos_feirantes/:feirante_id" => "home#produtos_feirantes", as: :produtos_feirantes
  get "home/anotacoes" => "home#anotacoes"
  get "home/adicionar/:produto_id" => "home#adicionar", as: :adicionar
  get "home/admin_homepage" => "home#admin_homepage", as: :home_admin_homepage
  get "home/feirante_homepage" => "home#feirante_homepage", as: :home_feirante_homepage
  get "home/admin_feirantes" => "home#admin_feirantes", as: :home_admin_feirantes

  get "login", to: "home#login"
  post "login", to: "home#authenticate"
  delete "logout", to: "home#logout"
  post "create_temp_user", to: "home#create_temp_user"
  post 'users/create_temp_user', to: 'users#create_temp_user'

  get "up" => "rails/health#show", as: :rails_health_check
end

feira/app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul>
      <% if current_admin %>
        <li><%= button_to 'Profile', edit_administrador_path(current_user), method: :get, class: 'button-confirm', style: 'margin: 5px;' %></li>
        <li><%= button_to 'Homepage', home_admin_homepage_path, method: :get, class: 'button-confirm', style: 'margin: 5px;' %></li>
      <% else %>
        <% if current_feirante %>
          <li><%= button_to 'Profile', edit_feirante_path(current_user), method: :get, class: 'button-confirm', style: 'margin: 5px;' %></li>
          <li><%= button_to 'Homepage', home_feirante_homepage_path, method: :get, class: 'button-confirm', style: 'margin: 5px;' %></li>
        <% else %>
          <% if current_user && !temp_user? %>
            <li><%= button_to 'Profile', edit_user_path(current_user), method: :get, class: 'button-confirm', style: 'margin: 5px;' %></li>
          <% end %>
          <li><%= button_to 'Homepage', home_feira_path, method: :get, class: 'button-confirm', style: 'margin: 5px;' %>
          <li><%= button_to 'Wish List', home_anotacoes_path, method: :get, class: 'button-confirm', style: 'margin: 5px;' %>
        <% end %>
      <% end %>
      <li>
        <%= button_to "Logout", logout_path, method: :delete, class: 'button-confirm', style: 'margin: 5px 5px 5px 5px;' %>
      </li>
    </ul>
  </nav>
</header>

feira/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Teste" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless (controller_name == 'home' && (action_name == 'login' || action_name == 'authenticate' || action_name == 'start_page') || controller_name == 'users' && (action_name == 'new' || action_name == 'create')) %>
      <%= render 'layouts/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>